### ISSUE TITLE
坐标在生存模式下显示错误

### ISSUE THREAD

**Issue by Spy096** [LordFokas/BlazeMap#79]
未知原因，坐标在创造模式下显示正常但是在生存模式下显示错误
![563ed9bbbdc47e49eff3822e94f32393](https://github.com/user-attachments/assets/2bb1dde0-bd4b-47b5-83c6-97e0b15ccad5)
![48f272e367a3898adef9599cf8991924](https://github.com/user-attachments/assets/0580b5ea-cf40-4065-a891-d8214db4ee6a)

**Comment by LordFokas** [comment]
Is this only in survival?

There's likely a mod interfering with our rendering routines.
We recently discovered EnhancedVisuals and ImmediatelyFast do this to our minimap.

**Comment by maddie-j** [comment]
Forgot to come back and update this. I believe a fix was released a few months back. Make sure you're on the latest version of both Blaze Map and EnhancedVisuals and it should now work 😊

**Comment by Gerbzzz** [comment]
Doing my writeup on 0.7, this is definitely not fixed yet. I have the same issue still appearing when Litematica tries to render text. Any time it renders text on screen, Blazemap has its text move over.

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/53b32929-bc12-488a-8a21-0e2868a08c7f" />

I have no clue what is causing it, I'm running numerous mods that I imagine interfere with rendering, but I'm not running  EnhancedVisuals nor ImmediatelyFast. It might be Embeddium or Nvidium, and I can try disabling either and both to see if it still happens.
